export hangup cause and put it in CDR reason/description
facebookincubator/CommunityCellularManager pull request #93
Opened 2018-02-28 02:17 UTC by eprueves

This gets the [hangup_cause value](https://wiki.freeswitch.org/wiki/Hangup_Causes) from the FS xml cdrs and includes them in the cdr description. 
Our intention for this is to get more info from calls, especially those zero-second calls that we see in the CDRs. This might be useful for others as well. 

CDR reason/description will now be in this format:
```
2 sec call to 639361234567 (outside_call/NORMAL_CLEARING)
0 sec call to 639361234567 (local_call/USER_BUSY)
0 sec call to 639361234567 (outside_call/RECOVERY_ON_TIMER_EXPIRE)
```

2018-02-28 13:46 UTC, 9muir commented
this looks useful, thanks.

2018-04-10 00:44 UTC, kkroo requested changes
Thanks for your contribution-- and for patiently waiting for a review
Please define this in a helper function that returns a default string "UNKNOWN" in <1% error case the field is missing and you get a list index error. We should still process the billing event regularly

2018-04-10 00:44 UTC, kkroo commented on client/core/federer_handlers/cdr.py
> +        hangupcause = get_tag_text(cdr_dom.getElementsByTagName("hangup_cause")[0].childNodes)
Thanks for your contribution-- and for patiently waiting for a review
Please define this in a helper function that returns a default string "UNKNOWN" in <1% error case the field is missing and you get a list index error. We should still process the billing event regularly

2018-04-11 05:41 UTC, eprueves commented
I modified the code based on the PR review and pushed those edits to this branch. 
Thanks!

2018-04-30 19:46 UTC, closed without merging